### ISSUE TITLE
Using http injector for tunneling

### ISSUE THREAD

**Issue by LikDev-256** [aleixrodriala/wa-tunnel#13]
I'm not exactly an expert on how it works but if you're on a WhatsApp only data plan. You can use the http injector app in the playstore to connect to a proxy server and get internet connection. It set's up a VPN.

I have seen this working pretty great having or 2Mbs. It avoids ISP speed restrictions too but I still don't know how it works. The payloads they use in the app are very secured and encrypted. Haven't able to peak how it works. Maybe I can get some info about how it works.

**Comment by aleixrodriala** [comment]
Maybe would be interesting but still would be out of scope of this project. This project is about tunneling TCP through WhatsApp messages not circumventing network restrictions.
