### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by yoonsio** [aleixrodriala/wa-tunnel#15]
It seems dangerous to leave this running on open internet.
Any plan on supporting some kind of authentication?

**Comment by aleixrodriala** [comment]
Sorry what do you mean? This software only forwards a port, if you want to use authentication on the proxy you must set it on the proxy itself. If you mean the traffic sent, is sent between 2 whatsapp accounts you have access only, encrypted E2E and also TLS encrypted in case you are using a proxy
